name: blog-generator

dependencies:
  - base == 4.*
  - haskell-say
library:
  source-dirs: src
executables:
  haskell-hello:
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - blog-generator
