name: blog-generator

dependencies:
  - base == 4.*
library:
  source-dirs: src

executables:
  blog-generator-exe:
    main: Main.hs
    ghc-options: -threaded -rtsopts -Wall -Werror
    dependencies:
    - blog-generator
